[[redirects]]
  # Redirect requests to the root page to the mock page, since it's what's actually available
  from = "/"
  to = "/mock"
  force = true
  status = 302

[[redirects]]
  # Redirect View requests to Mock, as the newer release
  from = "/view"
  to = "/mock"
  force = true
  status = 302

[[headers]]
  for = "/*"
  [headers.values]
    # https://xclacksoverhead.org
    X-Clacks-Overhead = "GNU Terry Pratchett"