[[redirects]]
  # Redirect Toolkit requests to the root
  from = "/toolkit"
  to = "/"
  force = true
  status = 301

[[redirects]]
  # Redirect Mock requests to the root
  from = "/mock"
  to = "/"
  force = true
  status = 301

[[redirects]]
  # Redirect Mock subpage requests to root pages
  from = "/mock/*"
  to = "/:splat"
  force = true
  status = 301

[[redirects]]
  # Redirect View requests to the root
  from = "/view"
  to = "/"
  force = true
  status = 301

[[redirects]]
  # Redirect View subpage requests to root pages
  from = "/view/*"
  to = "/:splat"
  force = true
  status = 301

[[headers]]
  for = "/*"
  [headers.values]
    # https://xclacksoverhead.org
    X-Clacks-Overhead = "GNU Terry Pratchett"